In [1]:
import pandas as pd

In [2]:
dtype = "counts"
moods_concat="/mnt/lab_data3/anusri/chrombpnet/results/chrombpnet/ATAC_PE/HEPG2/HEPG2_05.09.2022_bias_128_4_1234_0.8_fold_0/06_22_2022_motif_scanning/"
#moods_concat="/mnt/lab_data3/anusri/chrombpnet/results/chrombpnet/DNASE_PE/HEPG2/HEPG2_06.08.2022_bias_128_4_1234_0.8_fold_0/06_22_2022_motif_scanning/"

moods_concat=moods_concat + "moods/"+  dtype + "/all_metaclusters.all_patterns.hits.csv"

moods_dict = pd.read_csv(moods_concat, header=None)

display(moods_dict.head())
print()
display(moods_dict.shape)

moods_dict['peak_chrom'] = moods_dict[0].apply(lambda x: x.split(':')[0])
moods_dict['peak_start'] = moods_dict[0].apply(lambda x: x.split(':')[1].split("-")[0]).astype(int)
moods_dict['peak_end'] = moods_dict[0].apply(lambda x: x.split(':')[1].split("-")[1]).astype(int)
display(moods_dict.head())


moods_dict['pattern_chr'] = moods_dict['peak_chrom']
moods_dict['pattern_start'] = moods_dict['peak_start'] + moods_dict[2].astype(int)
moods_dict['pattern_end'] = moods_dict['pattern_start'] + moods_dict[5].apply(lambda x: len(x)).astype(int)
moods_dict['pattern_name'] = moods_dict[1].apply(lambda x: x.split('.pfm')[0])

moods_dict = moods_dict[['pattern_chr', 'pattern_start', 'pattern_end', 'pattern_name', 4, 3, 5, 'peak_chrom', 'peak_start', 'peak_end']]
moods_dict.columns = ['pattern_chr', 'pattern_start', 'pattern_end', 'pattern_name', 'score', 'strand', 'sequence', 'peak_chrom', 'peak_start', 'peak_end']

display(moods_dict.head())
print()
display(moods_dict.shape)

/users/anusri/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,0,1,2,3,4,5,6
0,chr1:100037138-100038138,metacluster_0.pattern_0.pfm.fwd.txt,971,+,9.72096,CCTCAAGATGGCGG,NaN
1,chr1:100037592-100038592,metacluster_0.pattern_0.pfm.fwd.txt,517,+,9.72096,CCTCAAGATGGCGG,NaN
2,chr1:100037855-100038855,metacluster_0.pattern_0.pfm.fwd.txt,254,+,9.72096,CCTCAAGATGGCGG,NaN
3,chr1:100132208-100133208,metacluster_0.pattern_0.pfm.fwd.txt,505,-,7.47622,CCGCCACCCGCGGG,NaN
4,chr1:100132856-100133856,metacluster_0.pattern_0.pfm.fwd.txt,351,+,7.31695,CCAGCTGAGGGTAG,NaN

(17111670, 7)

,0,1,2,3,4,5,6,peak_chrom,peak_start,peak_end
0,chr1:100037138-100038138,metacluster_0.pattern_0.pfm.fwd.txt,971,+,9.72096,CCTCAAGATGGCGG,NaN,chr1,100037138,100038138
1,chr1:100037592-100038592,metacluster_0.pattern_0.pfm.fwd.txt,517,+,9.72096,CCTCAAGATGGCGG,NaN,chr1,100037592,100038592
2,chr1:100037855-100038855,metacluster_0.pattern_0.pfm.fwd.txt,254,+,9.72096,CCTCAAGATGGCGG,NaN,chr1,100037855,100038855
3,chr1:100132208-100133208,metacluster_0.pattern_0.pfm.fwd.txt,505,-,7.47622,CCGCCACCCGCGGG,NaN,chr1,100132208,100133208
4,chr1:100132856-100133856,metacluster_0.pattern_0.pfm.fwd.txt,351,+,7.31695,CCAGCTGAGGGTAG,NaN,chr1,100132856,100133856

,pattern_chr,pattern_start,pattern_end,pattern_name,score,strand,sequence,peak_chrom,peak_start,peak_end
0,chr1,100038109,100038123,metacluster_0.pattern_0,9.72096,+,CCTCAAGATGGCGG,chr1,100037138,100038138
1,chr1,100038109,100038123,metacluster_0.pattern_0,9.72096,+,CCTCAAGATGGCGG,chr1,100037592,100038592
2,chr1,100038109,100038123,metacluster_0.pattern_0,9.72096,+,CCTCAAGATGGCGG,chr1,100037855,100038855
3,chr1,100132713,100132727,metacluster_0.pattern_0,7.47622,-,CCGCCACCCGCGGG,chr1,100132208,100133208
4,chr1,100133207,100133221,metacluster_0.pattern_0,7.31695,+,CCAGCTGAGGGTAG,chr1,100132856,100133856

(17111670, 10)

In [3]:
#tomtom = pd.read_csv("/oak/stanford/groups/akundaje/projects/chrombpnet_paper_new/DNASE_PE/HEPG2/HEPG2_06.08.2022_bias_128_4_1234_0.8_fold_0/SIGNAL/modisco_crop_500/" + dtype + ".tomtom.tsv", sep="\t")
tomtom = pd.read_csv("/oak/stanford/groups/akundaje/projects/chrombpnet_paper_new/ATAC_PE/HEPG2/HEPG2_05.09.2022_bias_128_4_1234_0.8_fold_0/SIGNAL/modisco_crop_500/" + dtype + ".tomtom.tsv", sep="\t")

In [4]:
tomtom.head()

,Pattern,Num_Seqlets,Match_1,q-value,Match_2,q-value.1,Match_3,q-value.2,Match_4,q-value.3,...,Match_6,q-value.5,Match_7,q-value.6,Match_8,q-value.7,Match_9,q-value.8,Match_10,q-value.9
0,metacluster_0.pattern_0,4515,CTCF_MA0139.1,1.765120e-19,CTCF_HUMAN.H11MO.0.A,6.763390e-13,CTCF_MOUSE.H11MO.0.A,4.667640e-12,CTCFL_HUMAN.H11MO.0.A,2.467940e-07,...,CTCF_C2H2_1,0.000001,CTCFL_MA1102.1,0.000011,ZIC2_MOUSE.H11MO.0.C,0.147865,ZIC3_HUMAN.H11MO.0.B,0.147865,ZIC3_MOUSE.H11MO.0.A,0.147865
1,metacluster_0.pattern_1,4017,HNF4G_MA0484.1,9.455560e-09,HNF4A_HUMAN.H11MO.0.A,3.499120e-07,HNF4G_HUMAN.H11MO.0.B,3.499120e-07,HNF4G_MOUSE.H11MO.0.C,3.499120e-07,...,HNF4A_nuclearreceptor_5,0.000090,Hnf4a.mouse_nuclearreceptor_1,0.000090,Hnf4a_MA0114.3,0.000090,HNF4A_nuclearreceptor_3,0.000176,HNF4A_nuclearreceptor_1,0.000183
2,metacluster_0.pattern_2,1555,FOXM1_HUMAN.H11MO.0.A,2.305980e-03,FOXM1_MOUSE.H11MO.0.B,2.305980e-03,Foxd3_MA0041.1,4.123400e-02,FOXJ2_HUMAN.H11MO.0.C,4.123400e-02,...,FOXA1_HUMAN.H11MO.0.A,0.059737,Foxc1.mouse_forkhead_1,0.059737,FOXC2_forkhead_2,0.059737,FOXA2_HUMAN.H11MO.0.A,0.059737,FOXP2_MA0593.1,0.059737
3,metacluster_0.pattern_3,1300,FOXP2_HUMAN.H11MO.0.C,6.693530e-04,FOXI1_MA0042.2,6.693530e-04,FOXI1_forkhead_1,6.693530e-04,FOXO6_MA0849.1,6.693530e-04,...,FOXO3_forkhead_1,0.000669,FOXO1_forkhead_2,0.000669,FOXO4_forkhead_1,0.000669,FOXO6_forkhead_1,0.000669,FOXO4_MA0848.1,0.000977
4,metacluster_0.pattern_4,991,ATF3_MOUSE.H11MO.0.A,3.927270e-03,FOS_HUMAN.H11MO.0.A,3.927270e-03,JUN_MOUSE.H11MO.0.A,3.927270e-03,BACH2_MOUSE.H11MO.0.A,3.927270e-03,...,JUNB_HUMAN.H11MO.0.A,0.003927,JUND_HUMAN.H11MO.0.A,0.003927,JUND_MOUSE.H11MO.0.A,0.003927,JUN_HUMAN.H11MO.0.A,0.003927,FOSL1_HUMAN.H11MO.0.A,0.003927

In [5]:
label_dict = {}

for index,row in tomtom.iterrows():
    label_dict[row['Pattern']] = row['Match_1']
        

moods_dict['tf'] = moods_dict['pattern_name'].apply(lambda x: label_dict[x] if x in label_dict else 'tbd')
moods_dict = moods_dict[["pattern_chr", "pattern_start", "pattern_end", "tf", "pattern_name",
                         "score", "strand", "sequence", "peak_chrom", "peak_start", "peak_end"]]

display(moods_dict.head())
print()
display(moods_dict.shape)

,pattern_chr,pattern_start,pattern_end,tf,pattern_name,score,strand,sequence,peak_chrom,peak_start,peak_end
0,chr1,100038109,100038123,CTCF_MA0139.1,metacluster_0.pattern_0,9.72096,+,CCTCAAGATGGCGG,chr1,100037138,100038138
1,chr1,100038109,100038123,CTCF_MA0139.1,metacluster_0.pattern_0,9.72096,+,CCTCAAGATGGCGG,chr1,100037592,100038592
2,chr1,100038109,100038123,CTCF_MA0139.1,metacluster_0.pattern_0,9.72096,+,CCTCAAGATGGCGG,chr1,100037855,100038855
3,chr1,100132713,100132727,CTCF_MA0139.1,metacluster_0.pattern_0,7.47622,-,CCGCCACCCGCGGG,chr1,100132208,100133208
4,chr1,100133207,100133221,CTCF_MA0139.1,metacluster_0.pattern_0,7.31695,+,CCAGCTGAGGGTAG,chr1,100132856,100133856

(17111670, 11)

In [6]:
#main_dir = "/mnt/lab_data3/anusri/chrombpnet/results/chrombpnet/DNASE_PE/HEPG2/HEPG2_06.08.2022_bias_128_4_1234_0.8_fold_0/06_22_2022_motif_scanning/moods/" + dtype
main_dir = "/mnt/lab_data3/anusri/chrombpnet/results/chrombpnet/ATAC_PE/HEPG2/HEPG2_05.09.2022_bias_128_4_1234_0.8_fold_0/06_22_2022_motif_scanning/moods/" + dtype

moods_dict.drop_duplicates().to_csv(main_dir+"/moods_scan_on_modisco_full.bed", sep="\t", header=False, index=False)